const names = [
  "C H I S HU",
  "Bruk Bro",
  "ሶፊያን Rejesteral",
  "Kocha",
  "Haydro Chiqu 40",
  "EYOBAA",
  "Kerimo Hiwi",
  "Yabu AA",
  "Ju Sultan",
  "Samual",
  "ታዲዎስ ተሾመ",
  "ousmi Ye Masre",
  "Md Hasen Familey",
  "Marta Gc Hrc",
  "Md Agatami",
  "Tenkol",
  "man thon",
  "MAEDA",
  "Man Yazewal",
  "M A M A Y E",
  "Ahmed Dorm",
  "ኡስማን",
  "kerimo ergo",
  "Abel Neo",
  "E Y O B A D Z",
  "Hassen Semera",
  "Tedaaa",
  "ሙሄ የሱፍ",
  "Joo Dz",
  "Redati",
  "Rediet",
  "Kfle Kasu Hrc",
  "Aziza A",
  "እብራሂም መስታወት ቤት",
  "chafa",
  "Mif Sis",
  "Hussen Abdu Qader",
  "Tpmg",
  "kayo",
  "Teguwaz",
  "Jose Tekaken",
  "Bzuye Garment",
  "M.d Jemle",
  "kerim mesgid jer",
  "Rahel Mek",
  "MD1",
  "Feyru 2",
  "san md",
  "Mehamedye Lenden Cafe",
  "Mala",
  "Bahru Rip",
  "Robit",
  "ሰአት የሚሞላ በዋስብ",
  "Anwar Fashin",
  "i'm A",
  "Benji Melataw",
  "ሰኝ",
  "Red Star",
  "Abrish Ticher",
  "Yasen. mo. d. ger",
  "Seyideee",
  "Esmail Kachur",
  "Ramse And",
  "Kedir Adem",
  "Fua 2",
  "Sirag",
  "Kedjit",
  "S E A D A",
  "Sera Nege Nx",
  "Nesibe Harerge",
  "Ekru Bemilew",
  "Kekua",
  "asagidow",
  "Estifo Hrc",
  "Miftah Afar",
  "ታቡራታ 21",
  "Qal Nech Sar",
  "M A N J A HU",
  "turab",
  "አቤኔዘር",
  "Naol ASTU",
  "Lula Hu",
  "Mogese",
  "Mehamed Shibash",
  "DAWITE JELASE ORO BANKER",
  "ALSI YAGERE LJ",
  "M d Yasufe",
  "Eusmane Sus",
  "E Jaki",
  "Shafi",
  "Seadi Yenefisa",
  "sadam yimam",
  "nuru mehamed",
  "Bini Sura",
  "Mebrat wotat",
  "Kd Dilak",
  "hospital",
  "selam Tena",
  "Nuru Tefera",
  "Mmanure",
  "ኤላም",
  "Kasu Hopa",
  "Nway Ict",
  "Smaf",
  "Muaz Sêfer",
  "M E R I Y E",
  "Dagi ancer",
  "M. d Abedl Hak",
  "Kabrom",
  "Kemal Jemal Se",
  "Husini Numan",
  "film",
  "Yenus Electron",
  "Oumer Pc",
  "Mebrat halafe",
  "Kutbaw",
  "Fasika Kinchilo",
  "Redi Ye Habib",
  "Yesuf Mebrat Hail",
  "Ebarhim Abdu",
  "Awele",
  "Mikoo",
  "Erahmiyaa",
  "My 1st",
  "Fz",
  "ሁሴን አሊ ወሌ",
  "ousman musa",
  "A K U S H A",
  "Aksume",
  "Qadre",
  "Cnc Machin",
  "Furniture Awol",
  "Aron Art......",
  "ኡዝታዝ መንሱር",
  "Shams",
  "Haji Teru",
  "Abubeker1",
  "M d Hayat",
  "Juhar Kintarot",
  "አኢሻ",
  "Abdulqadr Farm",
  "Aymen Qecho",
  "Tomas",
  "Kadra",
  "Hawa Endris Tezaz",
  "Inspire Ethiopia Therapy",
  "Osman Mebrat Pawer",
  "Qatar",
  "abdul Fetah Hajiye",
  "Mehemed",
  "Rahiel",
  "Ibrahim yusuf",
  "ከሪማ",
  "Kidist Shefraw Kidu",
  "Muba Sefer",
  "Ebre Transport",
  "Qafar Baxa Innikitino",
  "Hasna",
  "hasen Argobe",
  "M D Ibrahim",
  "Halima Musa",
  "Tilehun Wuha Wana Halafi",
  "Ginbu cyco",
  "አዊ",
  "Abdu Foka",
  "Md Meshe",
  "Feruz",
  "ሰኢድ �ሰን ዘይት",
  "Semira Sister",
  "CaaIMa, M d",
  "Bisness",
  "Fatuma hay",
  "Musa",
  "Abdu Mehamed",
  "Usman",
  "Fisaha",
  "Salahadin Kombolicha",
  "Bufe",
  "Kamil",
  "dani",
  "Habiba Frend",
  "ሙባረክ",
  "Hassenn",
  "Salahadin Ko 2",
  "Beyu",
  "Misk Megarejana Teras",
  "Lubaba",
  "+251 96 283 8966",
  "Hussen Mahe",
  "Ahmed Hussen",
  "ካሊድ አልመንሱር",
  "cemstri",
  "Hussen Awal",
  "Redwan tolha",
  "ኢመር",
  "F fi",
  "Yared Race",
  "Mesqeya",
  "Yasin mobile",
  "Nuru Jemal",
  "Eisa qasim",
  "Mohammed Abdukaadir",
  "Meri",
  "Mulugeta Teru",
  "kabe",
  "Abdulkerim",
  "Abas Be Masre1",
  "ጁሀር ሳኒ",
  "Endale Legese",
  "ጭድ ተራ",
  "ሀፊዝ",
  "side seraje",
  "Fozia seid",
  "Kit",
  "Yekbebat Teteri",
  "wale",
  "መሀመድ ዘይን ዶ/ር",
  "Kasim Shufer4",
  "Mamila",
  "ibrahim kamal",
  "usmi",
  "Ussu",
  "ኡስሚ",
  "Osman muhaba",
  "ali fa",
  "Nureye Sheta",
  "Faqe",
  "Ferehan Ambulans",
  "H I W I",
  "ኪችን",
  "V",
  "Sharif",
  "Anik Maou",
  "md meahmud",
  "Shambel M. Transport",
  "yerahmi Dorm Met",
  "Mohammed Hshem",
  "Ahmed yemam. ko",
  "Jmgjtddp",
  "ረደኤት",
  "husen adem",
  "Bela Bati",
  "Zekey mestawot",
  "Habib ali",
  "Class Met",
  "Z Laco",
  "anawar . buraq",
  "yealsa",
  "Mehamed yezumr",
  "ሰዋዲቅ ዙቤር",
  "semirrrr",
  "ሰለሞን ይትባረክ",
  "Loul seged",
  "Mikiyas Sefer",
  "Foziii tras",
  "Asru",
  "YE HIWET",
  "BIRUK MEWE",
  "kayredin",
  "Hussen behodu",
  "Mwm",
  "Zurt",
  "Oumer Ciramic",
  "Fanta",
  "eliyse",
  "manda",
  "pholisi eshuma",
  "JEMAL FREND",
  "Amir E",
  "Work",
  "Leboya",
  "yared dorm met",
  "anawr bajaj",
  "Zufan Nurye",
  "Fasika B. dar",
  "ከድጃ አሊ ወሌ ከንቲባ",
  "MR NAOL",
  "Desaleing meko",
  "Abdelaziz Dorm",
  "+251 91 333 4417",
  "Nuru Woderagi",
  "Endro Ka'anehu",
  "Customer 4",
  "Osama Abegar",
  "amachi",
  "Dewl",
  "Ami Chek",
  "mifatah migib",
  "Kaku",
  "Qasa",
  "yemimi Gbdaw Tlma",
  "ሩቅያ",
  "Jemal Quwachur",
  "Muktare Fren Jels",
  "ኑረዲን2",
  "Ruhiii",
  "Abdela Fw",
  "ሰይድ ኡመር",
  "may sister",
  "M.d Seid Usm",
  "Salim",
  "+251913361784",
  "Endalke Sus",
  "Ali Asefa",
  "Nure 40",
  "m d. s",
  "Hirut Mek",
  "Studio 1",
  "Yasin Bushera",
  "Sol Civil",
  "Dereje lebs. se",
  "J Foto Zebib",
  "Hawli",
  "Mahadii",
  "Seid Ye Nura",
  "Husen MhBrwe",
  "Remtiz",
  "Saed E",
  "Alene frend contracte",
  "Zubare",
  "እድሪስ የሱፍ",
  "Semira Eproxy",
  "Sua",
  "ENCHET MAJETY",
  "jemal Yasine",
  "Ahlam1",
  "Beruke Jelse Sudike",
  "Anu takashe",
  "Fm",
  "hamido",
  "Zebeba File",
  "ሀሚድ",
  "Lube Zemed",
  "Paf 2",
  "ሁሴን ሰይድ",
  "በህረድን",
  "ሱልጣን ሚኒ ሾፕ",
  "S hasen Kelem",
  "She endris NGD",
  "ግርማ ታደሰ ኢንቬስተር",
  "Medhane",
  "fthya",
  "MD afar 2",
  "kirea Ahe",
  "ክቤ",
  "Nuru Mulat",
  "ቡቲክ",
  "ustaz",
  "ዳአግም",
  "Kedir Shufer",
  "Fetiya Ruz",
  "Sead Bushra",
  "Halima",
  "Zxz5s",
  "Md karati",
  "Ayeman Mif",
  "ፎዚያ",
  "ቤዛ",
  "Toya",
  "Kalid Harer",
  "Eerehah Zekyu",
  "A,d Sani",
  "usman tarf",
  "YOSEF FB TR",
  "Lifestar",
  "Kadi",
  "መሀሙድ አብደል ሀቅ",
  "husan garj",
  "Fuade Kelsum",
  "Mahmude",
  "Mo d. yasenberu",
  "Rabiya",
  "Seid sheh. ahme",
  "0912700730",
  "Nejat yesuf",
  "ኢስማኤል አፋሩ",
  "Ahmad Lehadi",
  "kewulet Ali",
  "Badilu",
  "babi",
  "Allah",
  "Allah",
  "£mr",
  "Tutu",
  "Ahmadin",
  "Barok",
  "Lisànđro Màrťıŋež",
  "k............",
  "Abdul",
  "Đaህላk",
  "Jesse",
  "▀▄▀▄▀▄ Hard▄▀▄▀▄▀",
  "Neal",
  "😞",
  "enche 🤔",
  "Bi 🅜𝓸𝓼",
  "Tomï 👀",
  "Papa🐾",
  "🅚🅗🅐🅓🅘🅡",
  "Enchu🌱SEED🐾",
  "Dava",
  "🐤 M 🐈‍⬛🦉MyGate Network",
  "Shampa",
  "Pam+B",
  "🐸ጌት🍅",
  "Bærècho",
  "Afa",
  "Meko",
  "Dhugaa Sñ",
  "zebib",
  "adoni",
  "🐤Chewaw 🌱",
  "Ttinaaa",
  "tedygech “🌱SEED”",
  "Bulo",
  "90:00",
  "::::",
  "Gyij",
  "Ayub Eliyas",
  "Dubay Sheger",
  "Salah Furnitur",
  "Wendye Docter",
  "M/D AHMED",
  "Habiba Nuru",
  "Abahina",
  "Alektric Ebre",
  "Rrdeat",
  "Zehar 1",
  "ሳሚያ",
  "M.d Fyel Tebi",
  "adama delala",
  "tsegey",
  "Anwar Gbi",
  "Mame ali",
  "Cammadu",
  "Jafer",
  "M.Jud",
  "Bodaya",
  "mahamed Amin Husen",
  "Endatanesaw",
  "Amar 53",
  "Amina",
  "Keyria",
  "gambela",
  "kika",
  "jonah ⛹🏽‍♂️",
  "Bahi",
  "MÕ§",
  "Ela.camera",
  "Asmi",
  "Foziya",
  "Tawla Bet Enga Sefer",
  "Abdu Kaloyta",
  "Aziza md",
  "Luli",
  "Cusen Acmed",
  "Arebu Bajaj",
  "kulud 2",
  "M D Sheh",
  "Ahmed Husen Ar",
  "Bedru 04",
  "Mame Tawala",
  "Nohar",
  "Mehuba nuru",
  "Awash Balemuya",
  "Denu",
  "Dega wuha",
  "Minisha 06",
  "Habibi Mahandi",
  "ለምለም",
  "Yeshi",
  "ሙአዝ",
  "Qabdu Kaadr",
  "አካውንት",
  "ZAHRA BOLQO",
  "Astalow",
  "Kedija",
  "Bertukan Bertukan",
  "Wzef",
  "Tahir",
  "Babure",
  "Ahmedu",
  "Shibru",
  "Qabdu Qabar",
  "Barber",
  "Misbah Logiya",
  "cammadu wall",
  "Qali Lubak",
  "Wereda",
  "Camida yasen",
  "Hallo",
  "MD Qumar",
  "M d Chomye",
  "Ali Ahmed",
  "Tapi Stry",
  "Foziya yusuf",
  "Maedor",
  "Mohammed Ali",
  "habib Ibragim",
  "nuredin kemese",
  "Mehamed Seid",
  "abde Ismail",
  "Samiya Kassye",
  "Jemila",
  "Mehamed hussien",
  "Jon T",
  "osama",
  "Saliha Esmael",
  "Qalih maace",
  "YISE YE Ⓜ️🅰️N©️HE",
  "Frësh",
  "Ibaa",
  "Xinqe",
  "🐝🐝Lij",
  "Ğèñî🤭",
  "Er",
  "°",
  "Abrilo",
  "Dawed",
  "estif",
  "Yika",
  "Kari",
  "Guled Feysal 🐾",
  "Hiwi ab",
  "ꀘꀎꎭꍏꍏ ( ͡° ͜ʖ ͡°)",
  "Z W",
  "dagi",
  "Mod",
  "😎mame",
  "Kasem 🐾",
  "🐾Ab",
  "𝕍𝕚𝕡 𝕎𝕚𝕟𝕟𝕖𝕣🏆🏆",
  "dagi d",
  "Hai's",
  "Yeshialem🐾",
  "blen",
  "BMG",
  "Banta",
  "Kidist",
  "Huzey",
  "Yamach",
  "Fit 6",
  "Dandada😀",
  "Seya",
  "Gex",
  "Kimiyaa",
  "Balew",
  "Li~na🦋",
  "Murad",
  "Unowen",
  "Nurye Yimam",
  "F.M.T",
  "Ŝóme Øńe",
  "Yane",
  "Ifnan",
  "Nm, 👩‍❤️‍👨",
  "𝓶𝓲𝓱𝓻𝓮𝓽𝓪𝓫",
  "ÄŇŴÃŘ",
  "ÃPPLE Ɓãmıláẅ",
  "Mab",
  "SUSi",
  "ÃPLĒ ....",
  "dagi gaza",
  "Emily Rose",
  "እዚም እዛም ያው ነው🤔🤔",
  "El Cholo",
  "META",
  "Śâmĳ",
  "Lidetu",
  "11:11🌱",
  "Nnnnn",
  "Sa",
  "Wonderful",
  "ASEMERA ።።",
  "Hello",
  "Beri",
  "Terry",
  "@beki",
  "Yoba",
  "Mr.X",
  "ADE",
  "Lata",
  "fayisal",
  "Muller",
  "TEM",
  "Tomlin",
  "Tomlinson",
  "Fesel",
  "Hun",
  "XXX",
  "Jems",
  "Manuel",
  "Abule Man",
  "Kapital",
  "Devª 🐍",
  "Promax",
  "Lili",
  "Tazeb",
  "I know",
  "Mahlet",
  "Method",
  "Andrew",
  "Qwerty",
  "ዳግም",
  "@#🍅",
  "Esmish",
  "እያሙ",
  "𝓼𝓱𝓸𝓶𝓪𝓵𝓲𝓼𝓲",
  "Saiko",
  "Natan",
  "Åbė🐾",
  "Kejela",
  "ልዑል የፍቅር ሰው",
  "Xex7",
  "Begenaw",
  "Yeramada",
  "Dahjk",
  "teju",
  "Samsero",
  "tesfahun",
  "Mohamed",
  "Fit8",
  "D҈alu̾k̾a̾",
  "Abeba brand",
  "@yonatan",
  "Selom",
  "Wall Coman",
  "Zehara",
  "Bayu",
  "Degife",
  "Zack Man",
  "Ártéta",
  "Join",
  "𝑅𝑒̀𝑚𝑖",
  "RB",
  "§ilence 🥴",
  "የቢሆን አለም",
  "Mitu",
  "የኔ",
  "ሂሉሊያ😍",
  "A.B",
  "Kelemua",
  "Fhjffji",
  "Elias21",
  "ERKI 1",
  "Lena",
  "Bib",
  "Kan",
  "𝓵𝓲𝓵 𝔂𝓪𝓫",
  "FĮRĀ🐾",
  "JEMSI",
  "Fisha",
  "⎯꯭ ͜͡🌾⃝⃪⃔͜bad boy🐬͎̽𝆺꯭𝅥⎯꯭꯭",
  "Gug",
  "Dff",
  "Sinta",
  "Mercy",
  "THE THINKER BOY",
  "EYOB🇪🇹",
  "Hareg",
  "§ami",
  "THE THINKER BOY😕",
  "Gff",
  "Gh4h",
  "Oopppppp",
  "🅑🅘🅝🅨🅐🅜",
  "Marsimohi",
  "Mbb",
  "Tesfish",
];

module.exports = names;
